version: "3"
services:
  traefik:
    image: traefik:1.6.2
    container_name: traefik
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 8080:8080
      - 80:80
    networks:
      - web
networks:
  web:
    external: true
