################################################################
# Global configuration
################################################################
debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

################################################################
# Entrypoints configuration
################################################################
[entryPoints]
  [entryPoints.http]
    address = ":80"
    entryPoint = "http"

################################################################
# API and dashboard configuration
################################################################
[api]
  entrypoint="traefik"

################################################################
# Docker configuration backend
################################################################
[docker]
  exposedByDefault = false
